### ISSUE TITLE
Cannot set the disk_quota

### ISSUE THREAD

**Issue by skuppa** [cloudfoundry/cf-java-client#104]
We can have manifest with disk size when deploying application but it is not possible when we use API.  

```
applications:
- path: dist.zip
  instances: 1
  memory: 3G
  name: testapp
  disk: 3G
  domain: testdomain.com
  command: bin/start.sh
```

Can we add the feature or is it hidden somewhere?

Thanks,
-Sridharan
