### ISSUE TITLE
Minor issues in `ApplicationManifestUtils::toYaml`

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [cloudfoundry/cf-java-client#881]
There should be a null check around the `health-check-type` key, otherwise an NPE is thrown when a type isn't set:
https://github.com/cloudfoundry/cf-java-client/blob/516b00fe3ae989bde68d498853c368965d19cf0b/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/ApplicationManifestUtils.java#L346

Also, on OSX the YAML serializer doesn't render the path correctly. There should probably be a `toString` call here:
https://github.com/cloudfoundry/cf-java-client/blob/516b00fe3ae989bde68d498853c368965d19cf0b/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/ApplicationManifestUtils.java#L353
```
---
applications:
- health-check-type: port
  name: whatever
  path: !!sun.nio.fs.UnixPath {}
```
