### ISSUE TITLE
ApplicationManifestUtils.read() ignores docker properties in manifest yaml

### ISSUE THREAD

**Issue by chefhoobajoob** [cloudfoundry/cf-java-client#887]
Using these library dependencies:
```
    compile 'org.cloudfoundry:cloudfoundry-client-reactor:3.9.0.RELEASE'
    compile 'org.cloudfoundry:cloudfoundry-operations:3.9.0.RELEASE'
    compile 'io.projectreactor:reactor-core:3.1.5.RELEASE'
    compile 'io.projectreactor.ipc:reactor-netty:0.7.5.RELEASE'
```

With this manifest:
```
---
applications:
- name: my-app
  instances: 1
  memory: 2097M
  health-check-type: process
  disk_quota: 2048M
  docker:
    image: "<docker-registry>/<image-name>:latest"
  env:
    SOME_VARIABLE: someValue
```

This code:
```
        def manifests = ApplicationManifestUtils.read( pathToManifest)
        manifests.each { manifest ->
            println ">>> manifest:\n$manifest"
        }
```

...yields this manifest object:
```
>> manifest:
ApplicationManifest{buildpack=null, command=null, disk=2048, docker=null, domains=null, environmentVariables={SOME_VARIABLE=someValue}, healthCheckHttpEndpoint=null, healthCheckType=process, hosts=null, instances=1, memory=2097, name=my-app, noHostname=null,
 noRoute=null, path=null, randomRoute=null, routePath=null, routes=null, services=null, stack=null, timeout=null}
```

Note that the docker property is null above - the image has been ignored, and `pushManifest` fails with an NPE when it gets [here](https://github.com/cloudfoundry/cf-java-client/blob/156a521ec3ed74a7f072d72e16d612b57732b38d/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java#L413).
