### ISSUE TITLE
issue in ApplicationManifestUtils.write method 

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#911]
`ApplicationManifestUtils.write(OutputStream out, List<ApplicationManifest> applicationManifests)` **1.giving manifest in which memory does not have any unit of measurement.like M, MB, G, or GB.
2.path in output manifest is AbsolutePath .(expected is whatever available in old manifest).**

i used the following manifest to ```ApplicationManifestUtils.read```:
```
---
applications:
- name: apicomp
  memory: 1024M
  buildpack: java_buildpack
  instances: 1
  path: /Backend/demo-0.0.1-SNAPSHOT.jar
  random-route: true 
  services:
    - autodeployinst  
- name: uicomp
  memory: 1024M
  buildpack: staticfile_buildpack
  instances: 1
  path: /UI_Codes/dist/
  random-route: true 
```
then used
`ApplicationManifestUtils.write`  to  modify appName and got manifest output as:

```
---
applications:
- buildpack: java_buildpack
  instances: 1
  memory: 1024
  name: apicomp-green
  path: C:\Backend\demo-0.0.1-SNAPSHOT.jar
  random-route: true
  services:
  - autodeployinst
- buildpack: staticfile_buildpack
  instances: 1
  memory: 1024
  name: uicomp-green
  path: C:\UI_Codes\dist
  random-route: true
```
