### ISSUE TITLE
ApplicationManifestUtils thowing NumberFormatException

### ISSUE THREAD

**Issue by parasuram-tanguturu** [cloudfoundry/cf-java-client#968]
if memory/diskQuota contains any fraction digits like (1.4G ) ApplicationManifestUtils  throwing
**NumberFormatException**.

but CF CLI is supporting ,by  truncating decimal part. (i.e. drop everything after the decimal dot)
(for example:  for 125.9 MB it is taking 125MB)
example manifest used:
```
---
applications:
- name: bugfixcomp
  memory: 125.9M 
  disk_quota: 50M  
  buildpack: staticfile_buildpack
  instances: 1
  path: ./uicomp/bugfixcomp
  random-route: true
``` 
from CLI:
![image](https://user-images.githubusercontent.com/22343548/58858703-c4350880-86c5-11e9-8229-1833be2bcc01.png)

**issue at :
asMemoryInteger method (line 178 in ApplicationManifestUtils)**
https://github.com/cloudfoundry/cf-java-client/blob/caa1cb889cfe8717614c071703d833a1540784df/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/ApplicationManifestUtils.java#L187
